---
title: Summerside Community Choir
short_title: 
description: A Mixed-Voice Community Choir in Summerside, PEI Canada
baseurl: 
permalink: "/:path/"
defaults:
- scope:
    path: ''
  values:
    layout: page
- scope:
    path: ''
    type: posts
  values:
    layout: post
collections:
  people:
    output: true
    permalink: "/about/:path/"
  posts:
    output: true
    permalink: "/posts/:path/"
  projects:
    output: true
    permalink: "/projects/:path/"
jekyll-archives:
  enabled: all
  layout: archive
gems:
- jekyll-menus
- jekyll-archives
favicon: "/assets/img/favicon.png"
icons:
  feedburner: 
  twitter: summersidechoir
  gphotos: sumchoir
  500px: 
  tpt: 
  google_plus: 
  youtube: sumchoir
  email: info@summersidechoir.ca
  gitlab: 
  github: 
  bitbucket: 
  facebook: SummersideChoir
  tumblr: 
  behance: 
  dribbble: 
  flickr: 
  instagram: 
  linkedin: 
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange: 
  steam: 
  wordpress: 
